services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nutrient-tracker-app
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=applejuiceisgood1234$
      - DB_NAME=nutrient_checker
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: nutrient-tracker-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: applejuiceisgood1234$
      MYSQL_DATABASE: nutrient_checker
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:


